### ISSUE TITLE
Scale logos on Sponsor section

### ISSUE THREAD

**Issue by DcMac** [WarwickTECH/warwick.tech#20]
<img width="967" alt="screen shot 2017-02-21 at 19 26 35" src="https://cloud.githubusercontent.com/assets/15277765/23181165/cfcbaedc-f86b-11e6-91a4-96365cf10e6d.png">
Here's an example of how the logos should scale alongside eachother.

**Comment by emmadutton** [comment]
Done, ended up having the logos in 2 rows.
